baseURL = 'https://alexsandro.dev/'
languageCode = 'en'
defaultContentLanguage = 'pt-br'
title = 'Alexsandro'
theme = 'risotto'

[params]
noindex = false

[params.about]
title = "Alex"
description = "Engenheiro de dados, professor e entusiasta de Python."

[[params.socialLinks]]
url = "https://linkedin.com/in/Alexsandr0x"
title = "LinkedIn"
icon = "fa-brands fa-linkedin"

[[params.socialLinks]]
url = "https://github.com/Alexsandr0x"
title = "GitHub"
icon = "fa-brands fa-github"

[languages]
  [languages.pt-br]
    languageName = 'Português'
    weight = 1

    [[languages.pt-br.menu.main]]
      identifier = "about"
      name = "Sobre"
      url = "/about/"
      weight = 1

    [[languages.pt-br.menu.main]]
      identifier = "posts"
      name = "Posts"
      url = "/posts/"
      weight = 2

    [[languages.pt-br.menu.main]]
      identifier = "lessons"
      name = "Aulas e Apresentações"
      url = "/lessons/"
      weight = 3

  [languages.en]
    languageName = 'English'
    weight = 2

    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about/"
      weight = 1

    [[languages.en.menu.main]]
      identifier = "posts"
      name = "Posts"
      url = "/posts/"
      weight = 2

    [[languages.en.menu.main]]
      identifier = "lessons"
      name = "Lectures & Talks"
      url = "/lessons/"
      weight = 3

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = true
    noClasses = false

